/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by scripts/set-rn-version.js
 */

#pragma once

#include <cstdint>
#include <string_view>

namespace ABI50_0_0facebook::ABI50_0_0React {

constexpr struct {
  int32_t Major = 0;
  int32_t Minor = 73;
  int32_t Patch = 0;
  std::string_view Prerelease = "";
} reactNativeVersion;

} // namespace ABI50_0_0facebook::ABI50_0_0React
