/**
 * Automatically generated by expo-modules-autolinking.
 *
 * This autogenerated class provides a list of classes of native Expo modules,
 * but only these that are written in Swift and use the new API for creating Expo modules.
 */

import ABI50_0_0ExpoModulesCore
import ABI50_0_0ExpoVideo
import ABI50_0_0ExpoAppleAuthentication
import ABI50_0_0ExpoApplication
import ABI50_0_0EXAV
import ABI50_0_0ExpoBackgroundFetch
import ABI50_0_0EXBarCodeScanner
import ABI50_0_0ExpoBattery
import ABI50_0_0ExpoBlur
import ABI50_0_0ExpoBrightness
import ABI50_0_0ExpoCamera
import ABI50_0_0ExpoCellular
import ABI50_0_0ExpoClipboard
import ABI50_0_0EXConstants
import ABI50_0_0ExpoCrypto
import ABI50_0_0ExpoDevice
import ABI50_0_0ExpoDocumentPicker
import ABI50_0_0EASClient
import ABI50_0_0ExpoFileSystem
import ABI50_0_0ExpoGL
import ABI50_0_0ExpoHaptics
import ABI50_0_0ExpoImage
import ABI50_0_0ExpoImageManipulator
import ABI50_0_0ExpoImagePicker
import ABI50_0_0ExpoKeepAwake
import ABI50_0_0ExpoLinearGradient
import ABI50_0_0ExpoLocalAuthentication
import ABI50_0_0ExpoLocalization
import ABI50_0_0ExpoMailComposer
import ABI50_0_0ExpoNetwork
import ABI50_0_0ExpoPrint
import ABI50_0_0ExpoRandom
import ABI50_0_0ExpoHead
import ABI50_0_0ExpoScreenOrientation
import ABI50_0_0ExpoSecureStore
import ABI50_0_0ExpoSensors
import ABI50_0_0ExpoSharing
import ABI50_0_0ExpoSMS
import ABI50_0_0ExpoSpeech
import ABI50_0_0ExpoSQLite
import ABI50_0_0ExpoStoreReview
import ABI50_0_0ExpoSystemUI
import ABI50_0_0ExpoTrackingTransparency
import ABI50_0_0EXUpdates
import ABI50_0_0ExpoVideoThumbnails
import ABI50_0_0ExpoWebBrowser

@objc(ABI50_0_0ExpoModulesProvider)
public class ExpoModulesProvider: ModulesProvider {
  public override func getModuleClasses() -> [AnyModule.Type] {
    return [
      VideoModule.self,
      AppleAuthenticationModule.self,
      ApplicationModule.self,
      VideoViewModule.self,
      BackgroundFetchModule.self,
      BarCodeScannerModule.self,
      BatteryModule.self,
      BlurViewModule.self,
      BrightnessModule.self,
      CameraViewModule.self,
      CameraViewNextModule.self,
      CellularModule.self,
      ClipboardModule.self,
      ConstantsModule.self,
      CryptoModule.self,
      DeviceModule.self,
      DocumentPickerModule.self,
      EASClientModule.self,
      FileSystemModule.self,
      GLViewModule.self,
      HapticsModule.self,
      ImageModule.self,
      ImageManipulatorModule.self,
      ImagePickerModule.self,
      KeepAwakeModule.self,
      LinearGradientModule.self,
      LocalAuthenticationModule.self,
      LocalizationModule.self,
      MailComposerModule.self,
      NetworkModule.self,
      ExpoPrintModule.self,
      RandomModule.self,
      ExpoHeadModule.self,
      ScreenOrientationModule.self,
      SecureStoreModule.self,
      AccelerometerModule.self,
      BarometerModule.self,
      DeviceMotionModule.self,
      GyroscopeModule.self,
      MagnetometerModule.self,
      MagnetometerUncalibratedModule.self,
      PedometerModule.self,
      SharingModule.self,
      ExpoSMSModule.self,
      SpeechModule.self,
      SQLiteModule.self,
      SQLiteModuleNext.self,
      StoreReviewModule.self,
      ExpoSystemUIModule.self,
      TrackingTransparencyModule.self,
      UpdatesModule.self,
      VideoThumbnailsModule.self,
      WebBrowserModule.self
    ]
  }

  public override func getAppDelegateSubscribers() -> [ExpoAppDelegateSubscriber.Type] {
    return [
      FileSystemBackgroundSessionHandler.self,
      ExpoHeadAppDelegateSubscriber.self,
      ScreenOrientationAppDelegate.self,
      ExpoUpdatesAppDelegateSubscriber.self
    ]
  }

  public override func getReactDelegateHandlers() -> [ExpoReactDelegateHandlerTupleType] {
    return [
      (packageName: "expo-screen-orientation", handler: ScreenOrientationReactDelegateHandler.self),
      (packageName: "expo-updates", handler: ExpoUpdatesReactDelegateHandler.self)
    ]
  }
}
