
/**
 * This code was generated by [ABI50_0_0React-native-codegen](https://www.npmjs.com/package/ABI50_0_0React-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include <ABI50_0_0React/renderer/components/rncore/ABI50_0_0ShadowNodes.h>

namespace ABI50_0_0facebook {
namespace ABI50_0_0React {

extern const char AndroidHorizontalScrollContentViewComponentName[] = "AndroidHorizontalScrollContentView";
extern const char AndroidSwipeRefreshLayoutComponentName[] = "AndroidSwipeRefreshLayout";
extern const char PullToRefreshViewComponentName[] = "PullToRefreshView";
extern const char AndroidDrawerLayoutComponentName[] = "AndroidDrawerLayout";
extern const char ActivityIndicatorViewComponentName[] = "ActivityIndicatorView";
extern const char UnimplementedNativeViewComponentName[] = "UnimplementedNativeView";
extern const char SwitchComponentName[] = "Switch";
extern const char TraceUpdateOverlayComponentName[] = "TraceUpdateOverlay";

} // namespace ABI50_0_0React
} // namespace ABI50_0_0facebook
