
/**
 * This code was generated by [ABI50_0_0React-native-codegen](https://www.npmjs.com/package/ABI50_0_0React-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateCpp.js
 */
#include <ABI50_0_0React/renderer/components/rncore/ABI50_0_0States.h>

namespace ABI50_0_0facebook {
namespace ABI50_0_0React {



} // namespace ABI50_0_0React
} // namespace ABI50_0_0facebook
