
/**
 * This code was generated by [ABI50_0_0React-native-codegen](https://www.npmjs.com/package/ABI50_0_0React-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <ABI50_0_0React/renderer/components/rncore/ABI50_0_0EventEmitters.h>
#include <ABI50_0_0React/renderer/components/rncore/ABI50_0_0Props.h>
#include <ABI50_0_0React/renderer/components/rncore/ABI50_0_0States.h>
#include <ABI50_0_0React/renderer/components/view/ABI50_0_0ConcreteViewShadowNode.h>
#include <ABI50_0_0jsi/ABI50_0_0jsi.h>

namespace ABI50_0_0facebook {
namespace ABI50_0_0React {

JSI_EXPORT extern const char AndroidHorizontalScrollContentViewComponentName[];

/*
 * `ShadowNode` for <AndroidHorizontalScrollContentView> component.
 */
using AndroidHorizontalScrollContentViewShadowNode = ConcreteViewShadowNode<
    AndroidHorizontalScrollContentViewComponentName,
    AndroidHorizontalScrollContentViewProps,
    AndroidHorizontalScrollContentViewEventEmitter,
    AndroidHorizontalScrollContentViewState>;

JSI_EXPORT extern const char AndroidSwipeRefreshLayoutComponentName[];

/*
 * `ShadowNode` for <AndroidSwipeRefreshLayout> component.
 */
using AndroidSwipeRefreshLayoutShadowNode = ConcreteViewShadowNode<
    AndroidSwipeRefreshLayoutComponentName,
    AndroidSwipeRefreshLayoutProps,
    AndroidSwipeRefreshLayoutEventEmitter,
    AndroidSwipeRefreshLayoutState>;

JSI_EXPORT extern const char PullToRefreshViewComponentName[];

/*
 * `ShadowNode` for <PullToRefreshView> component.
 */
using PullToRefreshViewShadowNode = ConcreteViewShadowNode<
    PullToRefreshViewComponentName,
    PullToRefreshViewProps,
    PullToRefreshViewEventEmitter,
    PullToRefreshViewState>;

JSI_EXPORT extern const char AndroidDrawerLayoutComponentName[];

/*
 * `ShadowNode` for <AndroidDrawerLayout> component.
 */
using AndroidDrawerLayoutShadowNode = ConcreteViewShadowNode<
    AndroidDrawerLayoutComponentName,
    AndroidDrawerLayoutProps,
    AndroidDrawerLayoutEventEmitter,
    AndroidDrawerLayoutState>;

JSI_EXPORT extern const char ActivityIndicatorViewComponentName[];

/*
 * `ShadowNode` for <ActivityIndicatorView> component.
 */
using ActivityIndicatorViewShadowNode = ConcreteViewShadowNode<
    ActivityIndicatorViewComponentName,
    ActivityIndicatorViewProps,
    ActivityIndicatorViewEventEmitter,
    ActivityIndicatorViewState>;

JSI_EXPORT extern const char UnimplementedNativeViewComponentName[];

/*
 * `ShadowNode` for <UnimplementedNativeView> component.
 */
using UnimplementedNativeViewShadowNode = ConcreteViewShadowNode<
    UnimplementedNativeViewComponentName,
    UnimplementedNativeViewProps,
    UnimplementedNativeViewEventEmitter,
    UnimplementedNativeViewState>;

JSI_EXPORT extern const char SwitchComponentName[];

/*
 * `ShadowNode` for <Switch> component.
 */
using SwitchShadowNode = ConcreteViewShadowNode<
    SwitchComponentName,
    SwitchProps,
    SwitchEventEmitter,
    SwitchState>;

JSI_EXPORT extern const char TraceUpdateOverlayComponentName[];

/*
 * `ShadowNode` for <TraceUpdateOverlay> component.
 */
using TraceUpdateOverlayShadowNode = ConcreteViewShadowNode<
    TraceUpdateOverlayComponentName,
    TraceUpdateOverlayProps,
    TraceUpdateOverlayEventEmitter,
    TraceUpdateOverlayState>;

} // namespace ABI50_0_0React
} // namespace ABI50_0_0facebook
