/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class MeasureMode : uint8_t {
  Undefined = ABI50_0_0YGMeasureModeUndefined,
  Exactly = ABI50_0_0YGMeasureModeExactly,
  AtMost = ABI50_0_0YGMeasureModeAtMost,
};

template <>
constexpr inline int32_t ordinalCount<MeasureMode>() {
  return 3;
} 

template <>
constexpr inline int32_t bitCount<MeasureMode>() {
  return 2;
} 

constexpr inline MeasureMode scopedEnum(ABI50_0_0YGMeasureMode unscoped) {
  return static_cast<MeasureMode>(unscoped);
}

constexpr inline ABI50_0_0YGMeasureMode unscopedEnum(MeasureMode scoped) {
  return static_cast<ABI50_0_0YGMeasureMode>(scoped);
}

inline const char* toString(MeasureMode e) {
  return ABI50_0_0YGMeasureModeToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
