/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class Display : uint8_t {
  Flex = ABI50_0_0YGDisplayFlex,
  None = ABI50_0_0YGDisplayNone,
};

template <>
constexpr inline int32_t ordinalCount<Display>() {
  return 2;
} 

template <>
constexpr inline int32_t bitCount<Display>() {
  return 1;
} 

constexpr inline Display scopedEnum(ABI50_0_0YGDisplay unscoped) {
  return static_cast<Display>(unscoped);
}

constexpr inline ABI50_0_0YGDisplay unscopedEnum(Display scoped) {
  return static_cast<ABI50_0_0YGDisplay>(scoped);
}

inline const char* toString(Display e) {
  return ABI50_0_0YGDisplayToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
