/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class Align : uint8_t {
  Auto = ABI50_0_0YGAlignAuto,
  FlexStart = ABI50_0_0YGAlignFlexStart,
  Center = ABI50_0_0YGAlignCenter,
  FlexEnd = ABI50_0_0YGAlignFlexEnd,
  Stretch = ABI50_0_0YGAlignStretch,
  Baseline = ABI50_0_0YGAlignBaseline,
  SpaceBetween = ABI50_0_0YGAlignSpaceBetween,
  SpaceAround = ABI50_0_0YGAlignSpaceAround,
};

template <>
constexpr inline int32_t ordinalCount<Align>() {
  return 8;
} 

template <>
constexpr inline int32_t bitCount<Align>() {
  return 3;
} 

constexpr inline Align scopedEnum(ABI50_0_0YGAlign unscoped) {
  return static_cast<Align>(unscoped);
}

constexpr inline ABI50_0_0YGAlign unscopedEnum(Align scoped) {
  return static_cast<ABI50_0_0YGAlign>(scoped);
}

inline const char* toString(Align e) {
  return ABI50_0_0YGAlignToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
