/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class PositionType : uint8_t {
  Static = ABI50_0_0YGPositionTypeStatic,
  Relative = ABI50_0_0YGPositionTypeRelative,
  Absolute = ABI50_0_0YGPositionTypeAbsolute,
};

template <>
constexpr inline int32_t ordinalCount<PositionType>() {
  return 3;
} 

template <>
constexpr inline int32_t bitCount<PositionType>() {
  return 2;
} 

constexpr inline PositionType scopedEnum(ABI50_0_0YGPositionType unscoped) {
  return static_cast<PositionType>(unscoped);
}

constexpr inline ABI50_0_0YGPositionType unscopedEnum(PositionType scoped) {
  return static_cast<ABI50_0_0YGPositionType>(scoped);
}

inline const char* toString(PositionType e) {
  return ABI50_0_0YGPositionTypeToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
