/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class LogLevel : uint8_t {
  Error = ABI50_0_0YGLogLevelError,
  Warn = ABI50_0_0YGLogLevelWarn,
  Info = ABI50_0_0YGLogLevelInfo,
  Debug = ABI50_0_0YGLogLevelDebug,
  Verbose = ABI50_0_0YGLogLevelVerbose,
  Fatal = ABI50_0_0YGLogLevelFatal,
};

template <>
constexpr inline int32_t ordinalCount<LogLevel>() {
  return 6;
} 

template <>
constexpr inline int32_t bitCount<LogLevel>() {
  return 3;
} 

constexpr inline LogLevel scopedEnum(ABI50_0_0YGLogLevel unscoped) {
  return static_cast<LogLevel>(unscoped);
}

constexpr inline ABI50_0_0YGLogLevel unscopedEnum(LogLevel scoped) {
  return static_cast<ABI50_0_0YGLogLevel>(scoped);
}

inline const char* toString(LogLevel e) {
  return ABI50_0_0YGLogLevelToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
