/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class Overflow : uint8_t {
  Visible = ABI50_0_0YGOverflowVisible,
  Hidden = ABI50_0_0YGOverflowHidden,
  Scroll = ABI50_0_0YGOverflowScroll,
};

template <>
constexpr inline int32_t ordinalCount<Overflow>() {
  return 3;
} 

template <>
constexpr inline int32_t bitCount<Overflow>() {
  return 2;
} 

constexpr inline Overflow scopedEnum(ABI50_0_0YGOverflow unscoped) {
  return static_cast<Overflow>(unscoped);
}

constexpr inline ABI50_0_0YGOverflow unscopedEnum(Overflow scoped) {
  return static_cast<ABI50_0_0YGOverflow>(scoped);
}

inline const char* toString(Overflow e) {
  return ABI50_0_0YGOverflowToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
