/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class FlexDirection : uint8_t {
  Column = ABI50_0_0YGFlexDirectionColumn,
  ColumnReverse = ABI50_0_0YGFlexDirectionColumnReverse,
  Row = ABI50_0_0YGFlexDirectionRow,
  RowReverse = ABI50_0_0YGFlexDirectionRowReverse,
};

template <>
constexpr inline int32_t ordinalCount<FlexDirection>() {
  return 4;
} 

template <>
constexpr inline int32_t bitCount<FlexDirection>() {
  return 2;
} 

constexpr inline FlexDirection scopedEnum(ABI50_0_0YGFlexDirection unscoped) {
  return static_cast<FlexDirection>(unscoped);
}

constexpr inline ABI50_0_0YGFlexDirection unscopedEnum(FlexDirection scoped) {
  return static_cast<ABI50_0_0YGFlexDirection>(scoped);
}

inline const char* toString(FlexDirection e) {
  return ABI50_0_0YGFlexDirectionToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
