/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class Gutter : uint8_t {
  Column = ABI50_0_0YGGutterColumn,
  Row = ABI50_0_0YGGutterRow,
  All = ABI50_0_0YGGutterAll,
};

template <>
constexpr inline int32_t ordinalCount<Gutter>() {
  return 3;
} 

template <>
constexpr inline int32_t bitCount<Gutter>() {
  return 2;
} 

constexpr inline Gutter scopedEnum(ABI50_0_0YGGutter unscoped) {
  return static_cast<Gutter>(unscoped);
}

constexpr inline ABI50_0_0YGGutter unscopedEnum(Gutter scoped) {
  return static_cast<ABI50_0_0YGGutter>(scoped);
}

inline const char* toString(Gutter e) {
  return ABI50_0_0YGGutterToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
