/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class Dimension : uint8_t {
  Width = ABI50_0_0YGDimensionWidth,
  Height = ABI50_0_0YGDimensionHeight,
};

template <>
constexpr inline int32_t ordinalCount<Dimension>() {
  return 2;
} 

template <>
constexpr inline int32_t bitCount<Dimension>() {
  return 1;
} 

constexpr inline Dimension scopedEnum(ABI50_0_0YGDimension unscoped) {
  return static_cast<Dimension>(unscoped);
}

constexpr inline ABI50_0_0YGDimension unscopedEnum(Dimension scoped) {
  return static_cast<ABI50_0_0YGDimension>(scoped);
}

inline const char* toString(Dimension e) {
  return ABI50_0_0YGDimensionToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
