/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class Wrap : uint8_t {
  NoWrap = ABI50_0_0YGWrapNoWrap,
  Wrap = ABI50_0_0YGWrapWrap,
  WrapReverse = ABI50_0_0YGWrapWrapReverse,
};

template <>
constexpr inline int32_t ordinalCount<Wrap>() {
  return 3;
} 

template <>
constexpr inline int32_t bitCount<Wrap>() {
  return 2;
} 

constexpr inline Wrap scopedEnum(ABI50_0_0YGWrap unscoped) {
  return static_cast<Wrap>(unscoped);
}

constexpr inline ABI50_0_0YGWrap unscopedEnum(Wrap scoped) {
  return static_cast<ABI50_0_0YGWrap>(scoped);
}

inline const char* toString(Wrap e) {
  return ABI50_0_0YGWrapToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
