/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class ExperimentalFeature : uint8_t {
  WebFlexBasis = ABI50_0_0YGExperimentalFeatureWebFlexBasis,
  AbsolutePercentageAgainstPaddingEdge = ABI50_0_0YGExperimentalFeatureAbsolutePercentageAgainstPaddingEdge,
};

template <>
constexpr inline int32_t ordinalCount<ExperimentalFeature>() {
  return 2;
} 

template <>
constexpr inline int32_t bitCount<ExperimentalFeature>() {
  return 1;
} 

constexpr inline ExperimentalFeature scopedEnum(ABI50_0_0YGExperimentalFeature unscoped) {
  return static_cast<ExperimentalFeature>(unscoped);
}

constexpr inline ABI50_0_0YGExperimentalFeature unscopedEnum(ExperimentalFeature scoped) {
  return static_cast<ABI50_0_0YGExperimentalFeature>(scoped);
}

inline const char* toString(ExperimentalFeature e) {
  return ABI50_0_0YGExperimentalFeatureToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
