/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class NodeType : uint8_t {
  Default = ABI50_0_0YGNodeTypeDefault,
  Text = ABI50_0_0YGNodeTypeText,
};

template <>
constexpr inline int32_t ordinalCount<NodeType>() {
  return 2;
} 

template <>
constexpr inline int32_t bitCount<NodeType>() {
  return 1;
} 

constexpr inline NodeType scopedEnum(ABI50_0_0YGNodeType unscoped) {
  return static_cast<NodeType>(unscoped);
}

constexpr inline ABI50_0_0YGNodeType unscopedEnum(NodeType scoped) {
  return static_cast<ABI50_0_0YGNodeType>(scoped);
}

inline const char* toString(NodeType e) {
  return ABI50_0_0YGNodeTypeToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
