/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <ABI50_0_0yoga/ABI50_0_0YGEnums.h>
#include <ABI50_0_0yoga/enums/ABI50_0_0YogaEnums.h>

namespace ABI50_0_0facebook::yoga {

enum class Justify : uint8_t {
  FlexStart = ABI50_0_0YGJustifyFlexStart,
  Center = ABI50_0_0YGJustifyCenter,
  FlexEnd = ABI50_0_0YGJustifyFlexEnd,
  SpaceBetween = ABI50_0_0YGJustifySpaceBetween,
  SpaceAround = ABI50_0_0YGJustifySpaceAround,
  SpaceEvenly = ABI50_0_0YGJustifySpaceEvenly,
};

template <>
constexpr inline int32_t ordinalCount<Justify>() {
  return 6;
} 

template <>
constexpr inline int32_t bitCount<Justify>() {
  return 3;
} 

constexpr inline Justify scopedEnum(ABI50_0_0YGJustify unscoped) {
  return static_cast<Justify>(unscoped);
}

constexpr inline ABI50_0_0YGJustify unscopedEnum(Justify scoped) {
  return static_cast<ABI50_0_0YGJustify>(scoped);
}

inline const char* toString(Justify e) {
  return ABI50_0_0YGJustifyToString(unscopedEnum(e));
}

} // namespace ABI50_0_0facebook::yoga
