/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by an internal plugin build system
 */

#ifndef ABI50_0_0RN_DISABLE_OSS_PLUGIN_HEADER

// OSS-compatibility layer

#import "ABI50_0_0CoreModulesPlugins.h"

#import <string>
#import <unordered_map>

Class ABI50_0_0RCTCoreModulesClassProvider(const char *name) {
  // Intentionally leak to avoid crashing after static destructors are run.
  static const auto sCoreModuleClassMap = new const std::unordered_map<std::string, Class (*)(void)>{
    {"AccessibilityManager", ABI50_0_0RCTAccessibilityManagerCls},
    {"ActionSheetManager", ABI50_0_0RCTActionSheetManagerCls},
    {"AlertManager", ABI50_0_0RCTAlertManagerCls},
    {"AppState", ABI50_0_0RCTAppStateCls},
    {"Appearance", ABI50_0_0RCTAppearanceCls},
    {"Clipboard", ABI50_0_0RCTClipboardCls},
    {"DevLoadingView", ABI50_0_0RCTDevLoadingViewCls},
    {"DevMenu", ABI50_0_0RCTDevMenuCls},
    {"DevSettings", ABI50_0_0RCTDevSettingsCls},
    {"DeviceInfo", ABI50_0_0RCTDeviceInfoCls},
    {"EventDispatcher", ABI50_0_0RCTEventDispatcherCls},
    {"ExceptionsManager", ABI50_0_0RCTExceptionsManagerCls},
    {"I18nManager", ABI50_0_0RCTI18nManagerCls},
    {"KeyboardObserver", ABI50_0_0RCTKeyboardObserverCls},
    {"LogBox", ABI50_0_0RCTLogBoxCls},
    {"PerfMonitor", ABI50_0_0RCTPerfMonitorCls},
    {"PlatformConstants", ABI50_0_0RCTPlatformCls},
    {"RedBox", ABI50_0_0RCTRedBoxCls},
    {"SourceCode", ABI50_0_0RCTSourceCodeCls},
    {"StatusBarManager", ABI50_0_0RCTStatusBarManagerCls},
    {"Timing", ABI50_0_0RCTTimingCls},
    {"WebSocketExecutor", ABI50_0_0RCTWebSocketExecutorCls},
    {"WebSocketModule", ABI50_0_0RCTWebSocketModuleCls},
    {"BlobModule", ABI50_0_0RCTBlobManagerCls},
  };

  auto p = sCoreModuleClassMap->find(name);
  if (p != sCoreModuleClassMap->end()) {
    auto classFunc = p->second;
    return classFunc();
  }
  return nil;
}

#endif // ABI50_0_0RN_DISABLE_OSS_PLUGIN_HEADER
