
/*
 * This code was generated by [ABI50_0_0React-native-codegen](https://www.npmjs.com/package/ABI50_0_0React-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by GenerateABI50_0_0RCTThirdPartyFabricComponentsProviderH
 */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"

#import <ABI50_0_0React/ABI50_0_0RCTComponentViewProtocol.h>

#ifdef __cplusplus
extern "C" {
#endif

Class<ABI50_0_0RCTComponentViewProtocol> ABI50_0_0RCTThirdPartyFabricComponentsProvider(const char *name);

#ifndef ABI50_0_0RCT_DYNAMIC_FRAMEWORKS



#endif

#ifdef __cplusplus
}
#endif

#pragma GCC diagnostic pop

