
/**
 * This code was generated by [ABI50_0_0React-native-codegen](https://www.npmjs.com/package/ABI50_0_0React-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by GenerateABI50_0_0RCTThirdPartyFabricComponentsProviderCpp
 */

// OSS-compatibility layer

#import "ABI50_0_0RCTThirdPartyFabricComponentsProvider.h"

#import <string>
#import <unordered_map>

Class<ABI50_0_0RCTComponentViewProtocol> ABI50_0_0RCTThirdPartyFabricComponentsProvider(const char *name) {
  static std::unordered_map<std::string, Class (*)(void)> sFabricComponentsClassMap = {
    #ifndef ABI50_0_0RCT_DYNAMIC_FRAMEWORKS

    #endif
  };

  auto p = sFabricComponentsClassMap.find(name);
  if (p != sFabricComponentsClassMap.end()) {
    auto classFunc = p->second;
    return classFunc();
  }
  return nil;
}
