/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by an internal plugin build system
 */

#ifndef ABI50_0_0RN_DISABLE_OSS_PLUGIN_HEADER

// OSS-compatibility layer

#import "ABI50_0_0RCTFabricComponentsPlugins.h"

#import <string>
#import <unordered_map>

Class<ABI50_0_0RCTComponentViewProtocol> ABI50_0_0RCTFabricComponentsProvider(const char *name) {
  static std::unordered_map<std::string, Class (*)(void)> sFabricComponentsClassMap = {
    {"ActivityIndicatorView", ABI50_0_0RCTActivityIndicatorViewCls},
    {"InputAccessoryView", ABI50_0_0RCTInputAccessoryCls},
    {"Paragraph", ABI50_0_0RCTParagraphCls},
    {"PullToRefreshView", ABI50_0_0RCTPullToRefreshViewCls},
    {"SafeAreaView", ABI50_0_0RCTSafeAreaViewCls},
    {"ScrollView", ABI50_0_0RCTScrollViewCls},
    {"Switch", ABI50_0_0RCTSwitchCls},
    {"TextInput", ABI50_0_0RCTTextInputCls},
    {"UnimplementedNativeView", ABI50_0_0RCTUnimplementedNativeViewCls},
    {"View", ABI50_0_0RCTViewCls},
    {"Image", ABI50_0_0RCTImageCls},
    {"ModalHostView", ABI50_0_0RCTModalHostViewCls},
  };

  auto p = sFabricComponentsClassMap.find(name);
  if (p != sFabricComponentsClassMap.end()) {
    auto classFunc = p->second;
    return classFunc();
  }
  return ABI50_0_0RCTThirdPartyFabricComponentsProvider(name);
}

#endif // ABI50_0_0RN_DISABLE_OSS_PLUGIN_HEADER
